### ISSUE TITLE
[cdc-pipeline] Apply 'flink-confing' config for pipeline.

### ISSUE THREAD

**Issue by joyCurry30** [apache/flink-cdc#2854]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Our current task is to submit to the Flink cluster. Currently, the Flink configuration can only be read from 'FLINK_HOME' in the flink-conf.yaml file. This limitation is too restrictive, as it does not allow for flexible configuration of individual pipeline settings.

### Solution

Therefore, I suggest adding a configuration item, "flink-config," to the pipeline YAML configuration file. This will be used to configure Flink settings for individual pipeline.
The values in the "flink-config" configuration item will override those in flink-conf.yaml.

The 'flink-config' configuration items are as follows:
```yaml
flink-config:
  execution.checkpointing.interval: 30000
  execution.checkpointing.mode: EXACTLY_ONCE
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!
