### ISSUE TITLE
flink-cdc实时同步表时考虑过滤归档删除问题

### ISSUE THREAD

**Issue by chenrenfei** [apache/flink-cdc#3942]
### Please don't check the box below

- [x] I'm aware that bugs and new features should be reported on [Apache Jira](https://issues.apache.org/jira)  or Flink mailing list (dev@flink.apache.org) instead of here

### Again, please don't check the box below

- [x] I'm aware that new issues on GitHub will be ignored and automatically closed.

### 请不要勾选以下选项

- [x] 我已知悉缺陷和新功能需要在 [Apache Jira](https://issues.apache.org/jira) 或 Flink 邮件列表（dev@flink.apache.org）中反馈，而不是在这里创建新 issue。

### 也请不要勾选以下选项

- [x] 我已知悉 GitHub 上的新 issue 会被忽略且自动关闭。

**Comment by chenrenfei** [comment]
在flink-cdc同步业务数据库数据到数仓过程中，业务数据库会经常进行归档删除操作，但数仓的同步则需要区分归档删除和常规的业务删除，因此我们给流水表统一设计了：archivement_period(归档周期)字段，当该字段的值不为null时，希望删除操作flink-cdc过滤掉，逻辑即：
归档字段：archivement_period 或 is_archived 不为null，则过滤掉delete操作

**Comment by liuxuzxx** [comment]
> 在flink-cdc同步业务数据库数据到数仓过程中，业务数据库会经常进行归档删除操作，但数仓的同步则需要区分归档删除和常规的业务删除，因此我们给流水表统一设计了：archivement_period(归档周期)字段，当该字段的值不为null时，希望删除操作flink-cdc过滤掉，逻辑即： 归档字段：archivement_period 或 is_archived 不为null，则过滤掉delete操作

使用filter这个条件是否能够满足?

https://nightlies.apache.org/flink/flink-cdc-docs-release-3.5/zh/docs/core-concept/transform/  官方的transform中编写filter.看到官方的意思好像是满足了filter条件的都会被传递给下游, filter类似于where条件

```yaml
transform:
  - source-table: mydb.web_order
    filter: id > 10 AND order_id > 100  #只有满足id > 10的并且order_id > 100的才会被采集传递给下游
    description: filtering rows from source table
```
